#
#	Global configuration for Sheep makefiles
#

# Llama flags
LL_CFLAGS := -DLL_MEMORY_ONLY -DLL_NODE64
LL_LFLAGS := -ldl -Wl,-Bstatic -Wl,-Bdynamic

# Sheep flags
CC = mpic++
CXXFLAGS += -std=c++11 -fopenmp -g -rdynamic -Wall
CXXFLAGS += -O3 #-DNDEBUG
CXXFLAGS += ${LL_CFLAGS}
LDFLAGS  += ${LL_LFLAGS}
LIBS     += -lrt

